### ISSUE TITLE
Round trip the Cargo.toml better

### ISSUE THREAD

**Issue by wraithan** [wraithan/cargo-bump#1]
I'd like to bump the `package.version` field without changing anything else about the user's `Cargo.toml`. The technique most setups use to solve this is a round trip parser. Currently there are no round trip parsers for TOML in Rust. This means I am left with either building one, working on one of the in progress efforts, attempting to solve the problem in regex, or something else silly to preserve folks style/ordering/comments
## Stopgap

Until this hits 1.0 I'm not overly worried about getting this perfect. In the meantime I'm planning to just obliterate the user's Cargo.toml and generate one with `[package]` then `[dependencies]` then everything else to match common style.

There will need to be a clear warning about this in the readme and any other docs. It sucks but works well enough for my short term purposes.
## Possible Solution

@joelself's https://github.com/joelself/toml_parser is top choice right now since it is being built with this purpose in mind, actively being developed, and doesn't have history to contend with. But it is greenfield, currently not published to [crates.io](https://crates.io/), and doesn't support modification yet. Should I find myself squirrely enough to work on the round trip parsing problem, this is currently where I'd spend my effort.

https://github.com/alexcrichton/toml-rs is the most common parser solution for toml which I'm currently using. There is https://github.com/alexcrichton/toml-rs/pull/64 which looks to be adding this round trip ability, unfortunately the API ergonomics and code structure are still being debated and has been kinda dead for the last 6mo. Due to complexity and history, it is unlikely that I'd spend my time working on this.
## Other stuff

There is a [discourse thread](https://users.rust-lang.org/t/looking-for-a-project-how-about-a-toml-parser-that-writes-nice-files/3719) about this problem. Worth monitoring for new stuff to solve it. Before trying to make progress on this ticket check that thread.

**Comment by dannycoates** [comment]
> obliterate the user's Cargo.toml and generate one

As a user this feels like a potentially high price to pay for not much gain. I expect "bump" not "bump-and-reformat".

I bet you could have a regex solution pretty quickly and avoid the warning label. In the context of just "bump" it doesn't even seem *that* hacky. You're looking for a few specific tokens in a well structured file followed by a simple transformation; classic regex.

**Comment by wraithan** [comment]
`package.version` isn't the only `version = "string"` in many `Cargo.toml` writing an appropriate regex that won't get caught up in comments, strings, wrong sections, and different formatting styles seems like it would be much harder to debug.

Most folks are using git, so if they don't like the results they can just check out the version of their Cargo.toml from before and fix it and then tweet about how the tool is awful.

Rather take the easy way while there are 2 solutions on the horizon rather than take the hard way and burn a bunch of hours to be thrown away in a month or three. There are funner projects to work on.

**Comment by joelself** [comment]
I'm working as fast as I can. This is my #1 project right now. Unfortunately I was going through nom to add some functions and tests as a sort of thank you for providing the package and I found that the string macros (all of which have yet to be released) that I use throughout my parser are written as if bytes == chars (i.e. using functions that return a character offset to index into a byte array). So now I'm going through the `str` module and fixing everything up and writing tests with all non-ASCII characters to verify everything works with unicode.

Is it going to be a problem that you need nightly rust to compile the library? Because I can very easily scale it back to beta, but going all the way back to stable will take a more significant amount of time and if you need that I'd like to know sooner rather than later. I'm also using, as noted earlier, an unreleased version of nom.  I just have it configured to pull from the master branch from github (actually, now that I'm changing it it's pulling from a local directory). If nom doesn't release the `str` module and my changes by the time I'm ready for my first release I'll just have to pull from my own fork I guess.

**Comment by wraithan** [comment]
@joelself Rad! I hope I wasn't sounding impatient. Was more just excited that someone had recently started working on the problem and was making good progress.

Obviously the wider the version support is ideal, but for my own purposes I don't mind.too much since I use multirust personally. Beta would be pretty rad since that's likely to be stable soon, but if there is a performance difference I'd understand picking Nightly.

Vendoring `nom` or pulling from your own fork for a few early releases seems pretty reasonable. Geal seems pretty responsive so I'm sure it won't be for long.

Thanks again for working on toml_parser, I was pretty excited to not have to build one myself!

**Comment by joelself** [comment]
No, you didn't sound impatient. I just wanted everyone to know that I'm on top of it, but there are a few things slowing me down.

**Comment by joelself** [comment]
tomllib (I renamed toml_parser) is [out now at version 0.1.1](https://crates.io/crates/tomllib). It is currently limited to parsing documents, getting values, setting/changing values and getting subkeys of a key. From what I tell though cargo-bump gets the version, changes it, then sets the version, so this release should have everything you need to bump the version in a Cargo.toml while retaining all formatting and comments.
